### PR TITLE
Updated the proto support, fixed some perf issues and a few more things

### LINKED ISSUE #6: Return references instead of clones
Hey :wave:!

I saw that you wrote `// FIXME perf` in the sources and it seems that those are all related to cloning data. May I ask why the methods don't return references, allowing to the library's users to clone the returned data if wanted? :smiley:

Thank you :heart:!

### PR DESCRIPTION
**Pull request by azastrael**
Hey :wave:!

Here's what I did in this PR:
- The `proto` files were updated and a `build.rs` file to generate Rust code for them was added.
- The requests and responses were updated to support newly added fields.
- A few `unwraps` were removed to return `Result` instead.
- Support for using `Vec<u8>` as keys and values was added.
- Clients are now all `Clone`able and requests and responses (and their related types) now are `Debug`able and `Clone`able.
- A `KeepAlive` stream has been added. It is returned by one of two new methods of `LeaseClient`: `keep_alive` and `keep_alive_at_interval` (`keep_alive_once` has been removed).

Closes #6

### CODE REVIEW

**Comment by azastrael** [comment]
Hey :wave:!

So, I think this PR is ready for a review :smiley:

###### NOTE: I documented what I did in each commit in their description message.
###### NOTE: I'll finish removing all unwraps in an other PR where I'll also migrate the library to `std`'s futres.

**Comment by ccc13** [comment]
Hi, thanks for all the contributions you have done. :smile: 
I think it does not need to import gogo and some other thing which does not affect in Rust proto compiler. The API updates like `remove unwrap and return result` and `support low-level interactive` are great, but the backward-compatibility is broken.
As `async/await` will be available in the 1.39 release and [tonic](https://github.com/hyperium/tonic) emerges, I think it's time to embrace the new thing in `0.2` version. And for the `0.1` etcd-rs, I prefer not to release breaking changes. Correct me if I am wrong, thanks.

**Comment by azastrael** [comment]
> Hi, thanks for all the contributions you have done. 

Hey :wave:! :smile: 

> I think it does not need to import gogo and some other thing which does not affect in Rust proto compiler.

Right, I needed to because I wanted to use etcd's proto files as-is :smiley:

> The API updates like `remove unwrap and return result` and `support low-level interactive` are great, but the backward-compatibility is broken.
> 
> As `async/await` will be available in the 1.39 release and [tonic](https://github.com/hyperium/tonic) emerges, I think it's time to embrace the new thing in `0.2` version.
> 
> And for the `0.1` etcd-rs, I prefer not to release breaking changes. Correct me if I am wrong, thanks.

It makes complete sense to me! I would be glad to update the library to `tonic` and `async`/`await`, unless you would prefer to do it yourself.

Cheers!

**Comment by ccc13** [comment]
@azastrael master branch supports `async/await` and `tonic` now. Thanks again for this PR.

**Pull request closed without merging**
